/**
 * zk.ts — the role commitment.
 *
 * A player must commit a hidden role behind a Poseidon2 commitment before the
 * first round. Two halves, split by where they can safely run:
 *
 *   - the COMMITMENT is computed here, locally, because it is derived from a
 *     secret that must never leave this process;
 *   - the PROOF is generated by the game's public prover, because it needs the
 *     exact nargo/barretenberg pair the circuit was compiled with, and pinning
 *     that inside every agent would make writing an agent a build problem.
 *
 * That split is the one a third-party agent faces too, which is why the public
 * endpoint exists at all (see plague-celo docs/AGENTS.md).
 */
import { Barretenberg, Fr } from '@aztec/bb.js'
import { randomBytes } from 'node:crypto'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'
import type { Hex } from 'viem'

let bb: Barretenberg | null = null
async function getBB(): Promise<Barretenberg> {
  bb ??= await Barretenberg.new({ threads: 1 })
  return bb
}

function toField(v: bigint): Hex {
  return `0x${v.toString(16).padStart(64, '0')}`
}

/** Random 248-bit secret — always below the BN254 field modulus. */
function randomSecret(): bigint {
  return BigInt('0x' + randomBytes(31).toString('hex'))
}

export interface RoleProof {
  commitment: Hex
  proofHex: Hex
  /**
   * Kept so the commitment can be reopened later — an innocence proof needs the
   * role and secret behind it, and a commitment whose secret was discarded can
   * never be proven innocent. Low value on its own: the role is always 0
   * (clean), which every player commits and none of them hides.
   */
  secret: Hex
}

/**
 * Commitment + proof for role "clean" (0).
 *
 * Every player commits clean; infection is assigned by the game after the
 * start, not chosen by the player. Committing anything else would simply fail
 * to match what the game later asserts about you.
 *
 * Cached on disk and reused. Proving costs 30-120s of someone else's CPU, and
 * the commitment is not bound to a room, so regenerating per game would burn
 * the shared prover for no gain. If that binding is ever added upstream, this
 * cache is the thing that has to go.
 */
export async function loadRoleProof(cachePath: string, apiBase: string): Promise<RoleProof> {
  try {
    const cached = JSON.parse(await readFile(cachePath, 'utf8')) as RoleProof
    if (cached.commitment && cached.proofHex) return cached
  } catch {
    // No cache yet, or it is unreadable — generate a fresh one below.
  }

  const secret = randomSecret()
  const commitment = await computeCommitment(0n, secret)
  const proofHex = await requestProof(apiBase, {
    role: toField(0n), secret: toField(secret), commitment,
  })

  const proof: RoleProof = { commitment, proofHex, secret: toField(secret) }
  await mkdir(dirname(cachePath), { recursive: true })
  await writeFile(cachePath, JSON.stringify(proof, null, 2))
  return proof
}

/** commitment = poseidon2_permutation([role, secret, 0, 0])[0] — matches the Noir circuit. */
async function computeCommitment(role: bigint, secret: bigint): Promise<Hex> {
  const api = await getBB()
  const out = await api.poseidon2Permutation([new Fr(role), new Fr(secret), Fr.ZERO, Fr.ZERO])
  return toField(BigInt(out[0].toString()))
}

async function requestProof(
  apiBase: string, payload: { role: Hex; secret: Hex; commitment: Hex },
): Promise<Hex> {
  const ATTEMPTS = 4
  let resp!: Response

  for (let i = 0; i < ATTEMPTS; i++) {
    resp = await fetch(`${apiBase}/api/prove/role-commitment`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
    // The prover admits a fixed number of concurrent jobs and answers 503 +
    // Retry-After when saturated. That is "wait", not "failed" — giving up here
    // would forfeit a staked seat over a few seconds of queueing.
    if (resp.status !== 503 || i === ATTEMPTS - 1) break

    const header = Number(resp.headers.get('Retry-After'))
    const waitSecs = Number.isFinite(header) && header > 0 ? Math.min(header, 30) : 5
    await new Promise(r => setTimeout(r, waitSecs * 1000))
  }

  if (!resp.ok) {
    const body = await resp.json().catch(() => ({})) as { error?: string; detail?: string }
    throw new Error(body.detail ?? body.error ?? `prover returned HTTP ${resp.status}`)
  }
  const { proofHex } = await resp.json() as { proofHex: string }
  return (proofHex.startsWith('0x') ? proofHex : `0x${proofHex}`) as Hex
}
